api:
  insecure: true
  dashboard: true
serversTransport:
    insecureSkipVerify: true
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/selfsigned.crt
        keyFile: /etc/traefik/certs/selfsigned.key
  certificates:
    - certFile: /etc/traefik/certs/selfsigned.crt
      keyFile: /etc/traefik/certs/selfsigned.key
      stores:
        - default
